version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: distri-agents-pg-dev
    environment:
      POSTGRES_USER: distri
      POSTGRES_PASSWORD: distri
      POSTGRES_DB: distri_dev
      ALLOW_IP_RANGE: 0.0.0.0/0
    ports:
      - "5440:5432"
    command: postgres -c 'max_connections=1000'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: distri-agents-redis-dev
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/root/redis
    environment:
      - REDIS_PASSWORD=distri_password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
volumes:
  postgres_data:
  redis_data:
