agents:
  - id: "twitter_engagement"
    name: "Twitter Engagement"
    description: "Handles Twitter interactions including following, DMing, and replying"
    type: "tool"
    allowed_actions: 
      - "follow"
      - "dm"
      - "reply"
    provider_name: "twitter"
    model: "gpt-4"
    model_settings:
      temperature: 0.7
      max_tokens: 150

templates:
  - id: "promo-pete"
    name: "Promo Pete"
    description: |
      A go-getter bot that thrives on starting meaningful conversations to subtly promote your product."
      
    capabilities: ["twitter_engagement", "trend_analyzer"]
    default_settings:
      communication_style: "subtle_promotional"
      dm_enabled: true

  - id: "visionary-vera"
    name: "Visionary Vera"
    description: "Focused on shaping minds and spreading positivity within their niche."
    capabilities: ["twitter_engagement", "content_creator"]
    default_settings:
      content_types: ["thought_pieces", "polls", "commentary"]
      engagement_style: "reflective"

  - id: "flirty-fiona"
    name: "Flirty Fiona"
    description: "Witty and charming, loves sharing corny jokes and playful banter."
    capabilities: ["twitter_engagement", "content_creator"]
    default_settings:
      content_types: ["jokes", "memes", "banter"]
      engagement_style: "playful" 