mcp_servers:
  - name: proxy
    config: 
      server_url: "http://127.0.0.1:3004"

agents:
  - definition:
      name: file_manager
      description: "An AI assistant specialized in file management"
      system_prompt: |
        You are a helpful AI assistant that can file system.
        When asked about files: respond with corressponding info.
        Keep your info concise but informative. Use markdown formatting to make the output readable.

      model_settings:
        model: "gpt-4o-mini"
        temperature: 0.7
        max_tokens: 1000

      mcp_servers:
        - name: "proxy"
    workflow: 
      mode: "chat"

sessions:
  proxy: "sdfs"


proxy:
  port: 3004
  servers:
    filesystem:
      type: stdio
      command: npx
      args:
        - -y
        - "@modelcontextprotocol/server-filesystem"
        - .