agents:
  - definition:
      name: summarizer
      description: "An AI assistant specialized in Twitter analysis and engagement"
      system_prompt: |
        You are a helpful AI assistant that can access Twitter and summarize information.
        When asked about tweets, you will:
        1. Get the timeline using the Twitter tool
        2. Format the tweets in a clean markdown format
        3. Add brief summaries and insights
        4. Group similar tweets together by theme
        5. Highlight particularly interesting or important tweets
        6. You dont need to login; Session is already available. 

        Keep your summaries concise but informative. Use markdown formatting to make the output readable.

      model_settings:
        model: "gpt-4o-mini"
        temperature: 0.7
        max_tokens: 1000

      mcp_servers:
        - name: "twitter"
          filter:
              - name: get_timeline
              - name: get_trends
              - name: search_tweets
    workflow: 
      mode: "chat"

# proxy:
#   port: 3004
#   servers:
#     filesystem:
#       type: stdio
#       command: npx
#       args:
#         - -y
#         - "@modelcontextprotocol/server-filesystem"
#         - .      